branches:
  only:
  - master
services:
  - mssql2014
build_script:
- ps: ./build.ps1 -Target "AppVeyor"
test: off
artifacts:
- path: artifacts\nugets\*.nupkg
  name: nugets
- path: artifacts\v$(appveyor_build_version)\Ilaro.Admin.Sample
  name: Ilaro.Admin.Sample